- name: WakaTime
  uses: lowlighter/metrics@latest
  with:
    filename: metrics.plugin.wakatime.svg
    token: NOT_NEEDED
    base: ""  # This can be removed or set to a valid value
    plugin_wakatime: yes
    plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
    plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
